name: Matrix Build based on 2 arguments

on:
  push:
    branches: [ '*' ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.11', '3.12']
        debian_version: ['bookworm']
        variant: ['', '-slim']

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: ./aws/
          file: ./aws/Dockerfile
          push: false
          tags: user/appname:${{ matrix.apython_versionrg1 }}-${{ matrix.arg2 }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python_version }}
            DEBIAN_VERSION=${{ matrix.debian_version }}
            VARIANT=${{ matrix.variant }}
